language: node_js

sudo: required

env:
  - NODE_ENV=development

services:
  - redis-server

addons:
  mariadb: '10.4'

before_script:
  - sudo systemctl start mariadb
  - sudo mysql -u root < test/ci.sql
  - npm install codecov -g

jobs:
  include:
    - stage: Build
      node_js:
        - "8"
        - "10"
        - "12"
      script:
        - npm run-script build
    - stage: Lint
      script:
        - npm run-script lint
        - npm run-script tslint
    - stage: Test
      node_js:
        - "8"
        - "10"
        - "12"
      script:
        - npm run-script test-coverage

after_success:
  - codecov
